### ISSUE TITLE
Daylight bundle breaks loading of parameterized URLs

### ISSUE THREAD

**Issue by meyero** [conterra/mapapps-daylight#2]
**Reproduction:**
1. Create an app with a 2D map
2. add viewmodeswitcher, parameter-url and dn_daylight bundles
3. Open app, switch to 3D and change to a new perspective
4. Reload URL

**Expected result:**
- Map is started in 3D and shows the new perspective

**Actual result:**
- Map is shown in 2D
- viewmodeswitcher tool indicates a 3D map
- An error is printed in the browser's console: esri.core.Accessor] Accessor#set Assigning an instance of 'esri.views.MapView' which is not a subclass of 'esri.views.SceneView'

**Additional Hints:**
- App for testing available here: https://demos.conterra.de/sandbox/resources/apps/rvfm-test1/index.html?lang=de
- Reported by Regionalverband Frankfurt/Main

**Possible quick fixes:**
1. Prevent creating of the widget for MapViews
2. Add toolrule to "DaylightToggleTool" that tool is only available in 3D

**Comment by sholtkamp** [comment]
Fixed in "Hide DaylightToggleTool in 2d viewmode".
Released in version 1.1.1.
